# Generated by Django 5.1.3 on 2024-11-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="tasktype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[(4, "Urgent"), (3, "High"), (2, "Medium"), (1, "Low")]
            ),
        ),
    ]
