# Generated by Django 5.1.3 on 2024-11-17 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0002_alter_position_options_alter_tasktype_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-priority", "deadline"]},
        ),
    ]
